### PR TITLE
DOP-1579: Support for figure border flag

### PR DESCRIPTION
**Pull request by mango-db**
[DOP-1579](https://jira.mongodb.org/browse/DOP-1579).

Adds support for `:border:` flag in `figure` directive (and `image` directive by inheritance)

Bonus:
- Remove extraneous print()
- Add parser tests for `figure` and `atf-image` directives
- Remove extraneous spacing in options in `test_cardgroup()` and `test_required_option()`

### CODE REVIEW

**Review by i80and — COMMENTED** [review]
Do we actually need TIFF and JPEG2000 tests, and to test `image` separately?

**Comment by mango-db** [comment]
Figured they would be in the category of "nice to have" rather than strictly necessary! (Just in case someone is differentiating the functionality down the line). I defer to you, though!

**Comment by i80and** [comment]
I prefer not to have them, right now :D I'd rather keep the tests as focused as possible

**Review by sophstad — APPROVED** [review]
Just one change to make then LGTM!

**Pull request merged**
