### PR TITLE
DOP-3599 :fire: attempts to remove the position from the AST node used for snooty

### PR DESCRIPTION
**Pull request by caesarbell**
Removes the position field from the AST files, which was the request from [DOP-3599](https://jira.mongodb.org/browse/DOP-3599)

### Before
```js
doc {
  page_id: 'landing/caesarbell/master/openapi/preview',
  filename: 'openapi/preview.txt',
  ast: {
    type: 'root',
    position: { start: [Object] },
    children: [ [Object], [Object], [Object], [Object] ],
    fileid: 'openapi/preview.txt',
    options: {
      orphan: '',
      template: 'openapi',
      title: 'OpenAPI Styling Preview'
    }
  },
  source: ':orphan:\n' +
    '\n' +
    '.. meta::\n' +
    '   :robots: noindex\n' +
    ' \n' +
    ':template: openapi\n' +
    ':title: OpenAPI Styling Preview\n' +
    '\n' +
    '.. default-domain:: mongodb\n' +
    '\n' +
    '.. banner:: \n' +
    '   :variant: info\n' +
    '\n' +
    "   This page is intended for previewing OpenAPI spec files with the styling of MongoDB's documentation. The contents may not reflect actual endpoints or services.\n" +
    '\n' +
    '.. openapi:: /openapi/loremipsum.json\n' +
    '   :preview:\n',
  static_assets: []
}
```

```js
pageNodes {
  type: 'root',
  position: { start: { line: 0 } },
  children: [
    {
      type: 'directive',
      position: [Object],
      children: [Array],
      domain: '',
      name: 'ia',
      argument: []
    },
    {
      type: 'directive',
      position: [Object],
      children: [],
      domain: '',
      name: 'search-results',
      argument: []
    }
  ],
  fileid: 'search.txt',
  options: {
    template: 'landing',
    'nav-show-all-products': 'true',
    title: 'Docs Home',
    ia: [ [Object], [Object], [Object], [Object] ]
  }
}
```

### Afrer
```js
doc {
  page_id: 'landing/caesarbell/master/openapi/preview',
  filename: 'openapi/preview.txt',
  ast: {
    type: 'root',
    children: [ [Object], [Object], [Object], [Object] ],
    fileid: 'openapi/preview.txt',
    options: {
      orphan: '',
      template: 'openapi',
      title: 'OpenAPI Styling Preview'
    }
  },
  source: ':orphan:\n' +
    '\n' +
    '.. meta::\n' +
    '   :robots: noindex\n' +
    ' \n' +
    ':template: openapi\n' +
    ':title: OpenAPI Styling Preview\n' +
    '\n' +
    '.. default-domain:: mongodb\n' +
    '\n' +
    '.. banner:: \n' +
    '   :variant: info\n' +
    '\n' +
    "   This page is intended for previewing OpenAPI spec files with the styling of MongoDB's documentation. The contents may not reflect actual endpoints or services.\n" +
    '\n' +
    '.. openapi:: /openapi/loremipsum.json\n' +
    '   :preview:\n',
  static_assets: []
}
```
output is a log from [doc](https://github.com/mongodb/snooty/blob/e78bdec16760162eee411b3b517f2179e7d9f87f/gatsby-node.js#L112) variable
```js
pageNodes {
  type: 'root',
  children: [
    {
      type: 'directive',
      children: [Array],
      domain: '',
      name: 'ia',
      argument: []
    },
    {
      type: 'directive',
      children: [],
      domain: '',
      name: 'search-results',
      argument: []
    }
  ],
  fileid: 'search.txt',
  options: {
    template: 'landing',
    'nav-show-all-products': 'true',
    title: 'Docs Home',
    ia: [ [Object], [Object], [Object], [Object] ]
  }
}
```
output is a log from [pageNode](https://github.com/mongodb/snooty/blob/e78bdec16760162eee411b3b517f2179e7d9f87f/gatsby-node.js#L230) variable

### CODE REVIEW

**Review by seungpark — APPROVED** [review]
this LGTM! minor note on removing line

**Comment by i80and** [comment]
I don't think we want to remove position data from the AST in the parser -- that position data isn't used for anything downstream right now, but removing it makes some interesting things we could do[1] that much harder.

I think there are two good options here, either would be okay with me:
1) Making an environment variable or an option to snooty to tell it not to emit position data (avoids full AST traversal), or
2) Removing position data in the frontend (lower stack complexity, my preferred solution)

I'm open to being overridden on this if we just want to reduce the data being created and shuttled around ASAP: this PR does do that correctly and efficiently!

cc @rayangler @schmalliso

[1]: e.g. in staging hovering over a text element could show the source file path and line

**Comment by rayangler** [comment]
Removing the `position` field in the frontend prior to page creation might be more beneficial for now. Since the persistence module currently uploads all page ASTs as-is in the database, the `position` field may be good to have for any debugging/auditing purposes

**Comment by caesarbell** [comment]
> Removing the `position` field in the frontend prior to page creation might be more beneficial for now. Since the persistence module currently uploads all page ASTs as-is from the parser to the database, the `position` field may be good to have for any debugging/auditing purposes

@rayangler with more context, we would want to remove `position` prior to page creation via the `createPage` method. An example would be traversing the `pageNodes` object and removing the `position` fields. Or actually probably address the concern in sourcing of nodes

**Comment by caesarbell** [comment]
Going to close this PR as the solution will not reside in the parser.

**Pull request closed without merging**
