### PR TITLE
DOP-4404: Warn about orphan pages

### PR DESCRIPTION
**Pull request by i80and**
### Ticket

DOP-4404

### Notes

Guides and IA references are deliberately not inspected. This is a writer-facing change: the server manual has 25 instances:

* `index.txt`
* `administration/free-monitoring.txt`
* `administration/install-on-linux.txt`
* `core/indexes/index-types/geospatial/geohaystack.txt`
* `includes/featureCompatibility-caveat.txt`
* `includes/downgrade-for-set-cluster-parameter.txt`
* `includes/in-use-encryption/admonition-csfle-key-rotation.txt`
* `includes/qe-tutorials/python/requirements.txt`
* `reference/command/mergeAllChunksOnShard.txt`
* `reference/command/compactStructuredEncryptionData.txt`
* `reference/method/hostname.txt`
* `reference/method/copyDbpath.txt`
* `reference/method/Bulk.find.delete.txt`
* `reference/method/KeyVault.addKeyName.txt`
* `reference/method/db.getLastError.txt`
* `reference/method/db.getLastErrorObj.txt`
* `reference/method/KeyVault.createDataKey.txt`
* `reference/method/Bulk.find.deleteOne.txt`
* `reference/method/resetDbpath.txt`
* `reference/method/js-native.txt`
* `reference/method/KeyVault.removeKeyAltName.txt`
* `reference/method/db.collection.compactStructuredEncryptionData.txt`
* `tutorial/build-a-2d-index.txt`
* `tutorial/query-a-2d-index.txt`
* `tutorial/query-a-2dsphere-index.txt`

### README updates

- - [ ] This PR introduces changes that should be reflected in the README.md and/or HACKING.md, and I have made those updates.
- - [ ] This PR does not introduce changes that should be reflected in the README.md and/or HACKING.md

### CODE REVIEW

**Review by rayangler — APPROVED** [review]
LGTM! Ran this on `cloud-docs` and saw 377 instances of the warning 😱

**Comment by i80and** [comment]
Ech. Writers won't appreciate 377 additional warnings. I don't think we can merge this without some more thought/conversation

**Comment by i80and** [comment]
It looks like there are a LOT of incorrectly named/placed pages in the cloud-docs corpus

**Comment by i80and** [comment]
I've opted to add an option to silence select diagnostics. This should mostly never be used, but this feature SHOULD go out, and SHOULD NOT be blocked by the atlas docs.

**Comment by i80and** [comment]
Question for discussion: should the option to silence this diagnostic be in snooty.toml (i.e. in the repository) or in rstspec.toml (i.e. under our own control)

**Pull request merged**
